### PR TITLE
Closes #114 Fix incorrect logic in set_variable_labels()

### LINKED ISSUE #114: Fix incorrect logic in set_variable_labels() for detecting variable mismatches
The current logic in `set_variable_labels()` for detecting variables that exist in metadata but not in data (and vice versa) is incorrect.

Current logic:
```
mismatch <- setdiff(dns, ns)
in_meta <- ns[which(ns %in% mismatch)]
in_data <- dns[which(dns %in% mismatch)]
```

`mismatch` contains variables in data but NOT in metadata. We want to be able to detect both

Logic to update:
```
in_meta <- setdiff(ns, dns)  # Variables in metadata not in data
in_data <- setdiff(dns, ns)  # Variables in data not in metadata
```

### PR DESCRIPTION
**Pull request by jeffreyad**
Fix label logic, add test file and also correct a misspelling in the test file

### CODE REVIEW

File: tests/testthat/test-labels.R [hunk 1]
```diff
@@ -119,7 +119,7 @@ test_that("set_variable_labels raises warnings properly", {
 
 })
 
-test_that("removal_labels works to remvoe all labels", {
+test_that("removal_labels works to remove all labels", {
```
Comment (bms63) [inline tests/testthat/test-labels.R]:
```suggestion
test_that("remove_labels works to remove all labels", {
```

found another!!
